language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-23.0.2
    - android-23

    # Additional components
    #    - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
    #    - addon-google_apis-google-23  

script:
  ./gradlew build