apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'kotlin-allopen'

allOpen {
    annotation 'cat.xlagunas.core.OpenClass'
}

android {
    namespace 'cat.xlagunas.core'
    compileSdk 34

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "cat.xlagunas.viv.commons.cat.xlagunas.core.di.MockTestRunner"
    }

    buildFeatures {
        buildConfig = true
    }

    flavorDimensions "version"

    productFlavors {
        production {
            buildConfigField "String", "ENDPOINT", '"https://api.viv.xlagunas.dev"'
        }

        development {
            versionNameSuffix '.local'
            buildConfigField "String", "ENDPOINT", '"http://192.168.0.159:8080"'
        }
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }


    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas".toString())
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    ksp 'com.google.dagger:dagger-compiler:2.51.1'
    implementation 'com.google.dagger:dagger:2.51.1'

    ksp 'androidx.room:room-compiler:2.6.1'
    implementation 'androidx.room:room-runtime:2.6.1'
    implementation 'androidx.room:room-rxjava2:2.6.1'

    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-reactivestreams:2.8.7'

    implementation 'com.google.android.material:material:1.12.0'

    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.7'

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.jakewharton.timber:timber:5.0.1'
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.11.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'

    debugApi 'com.github.chuckerteam.chucker:library:4.0.0'
    releaseApi 'com.github.chuckerteam.chucker:library-no-op:4.0.0'

    implementation 'androidx.core:core-ktx:1.13.1'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}