name: Android CI

on:
  push:
    branches: [ kotlin, add_github_actions ]
  pull_request:
    branches: [ kotlin, add_github_actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decode google-services.json
      env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          PROD_KEYSTORE_PASSWORD: ${{secrets.PROD_KEYSTORE_PASSWORD}}
          PROD_KEY_ALIAS: ${{PROD_KEY_ALIAS}}
          PROD_KEY_PASSWORD: ${{PROD_KEY_PASSWORD}}
      run: echo $GOOGLE_SERVICES > app/google-services.json
    - name: Build with Gradle
      run: ./gradlew build
